[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/desktop.html"
  to = "/desktop.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
